// SPDX-License-Identifier: Apache-2.0

package lsp

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rchekalov/silo/internal/config"
	"github.com/rchekalov/silo/internal/errs"
)

// GenerateIDEConfig writes IDE-specific LSP glue into `projectDir`. `tools` is
// filtered to tools with an LspConfig.
func GenerateIDEConfig(ide string, tools map[string]config.ToolDefinition, projectDir string) error {
	lspTools := map[string]config.ToolDefinition{}
	for k, v := range tools {
		if v.LSP != nil {
			lspTools[k] = v
		}
	}
	if len(lspTools) == 0 {
		fmt.Fprintln(os.Stderr, "No installed tools have LSP configuration.")
		return nil
	}
	switch strings.ToLower(ide) {
	case "vscode":
		return generateVSCode(lspTools, projectDir)
	case "zed":
		return generateZed(lspTools, projectDir)
	case "neovim", "nvim":
		return generateNeovim(lspTools, projectDir)
	default:
		return errs.Configf("unsupported IDE %q. Supported: vscode, zed, neovim", ide)
	}
}

func generateVSCode(tools map[string]config.ToolDefinition, projectDir string) error {
	dir := filepath.Join(projectDir, ".vscode")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(dir, "settings.json")
	settings := readJSONObject(path)

	for name := range tools {
		switch name {
		case "python":
			settings["python.languageServer"] = "None"
			home, _ := os.UserHomeDir()
			if home != "" {
				settings["python.defaultInterpreterPath"] = filepath.Join(home, ".silo", "bin", "python")
			} else {
				settings["python.defaultInterpreterPath"] = "~/.silo/bin/python"
			}
		case "node":
			settings["typescript.tsdk"] = ""
		}
	}
	if err := writeJSON(path, settings); err != nil {
		return err
	}
	fmt.Fprintln(os.Stderr, "Generated .vscode/settings.json")
	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "Configure your LSP servers in VS Code:")
	for _, name := range sortedKeys(tools) {
		fmt.Fprintf(os.Stderr, "  Language server for %s: silo lsp %s\n", name, name)
	}
	return nil
}

func generateZed(tools map[string]config.ToolDefinition, projectDir string) error {
	dir := filepath.Join(projectDir, ".zed")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(dir, "settings.json")
	settings := readJSONObject(path)
	lsp, _ := settings["lsp"].(map[string]any)
	if lsp == nil {
		lsp = map[string]any{}
	}
	for _, name := range sortedKeys(tools) {
		t := tools[name]
		server := name
		if len(t.LSP.Command) > 0 {
			server = t.LSP.Command[0]
		}
		lsp[server] = map[string]any{
			"binary": map[string]any{
				"path":      "silo",
				"arguments": []string{"lsp", name},
			},
		}
	}
	settings["lsp"] = lsp
	if err := writeJSON(path, settings); err != nil {
		return err
	}
	fmt.Fprintln(os.Stderr, "Generated .zed/settings.json")
	return nil
}

func generateNeovim(tools map[string]config.ToolDefinition, projectDir string) error {
	serverMap := map[string]string{
		"python": "pyright",
		"node":   "ts_ls",
		"rust":   "rust_analyzer",
		"go":     "gopls",
	}
	var b strings.Builder
	b.WriteString("-- Silo LSP configuration (generated by silo ide neovim)\n")
	b.WriteString("-- Source this file from your init.lua:\n")
	b.WriteString("--   dofile(vim.fn.getcwd() .. '/.nvim-silo.lua')\n\n")
	b.WriteString("local lspconfig = require('lspconfig')\n\n")

	for _, name := range sortedKeys(tools) {
		server := serverMap[name]
		if server == "" {
			server = name
		}
		fmt.Fprintf(&b, "lspconfig.%s.setup({\n  cmd = { 'silo', 'lsp', '%s' },\n})\n\n", server, name)
	}

	path := filepath.Join(projectDir, ".nvim-silo.lua")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Fprintln(os.Stderr, "Generated .nvim-silo.lua")
	fmt.Fprintln(os.Stderr, "Add to your init.lua:")
	fmt.Fprintln(os.Stderr, "  dofile(vim.fn.getcwd() .. '/.nvim-silo.lua')")
	return nil
}

func sortedKeys(m map[string]config.ToolDefinition) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// readJSONObject loads a JSON object from path, or returns an empty map.
func readJSONObject(path string) map[string]any {
	raw, err := os.ReadFile(path)
	if err != nil {
		return map[string]any{}
	}
	var out map[string]any
	if err := json.Unmarshal(raw, &out); err != nil || out == nil {
		return map[string]any{}
	}
	return out
}

func writeJSON(path string, v any) error {
	raw, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, raw, 0o644)
}
